In [1]:
 # Import NumPy for numerical operations
import numpy as np



In [2]:
#Binary Classification(True & Predicted Values)
 #Actual labels (ground truth)
y_true = np.array([1, 0, 0, 1, 1])
# Predicted probabilities
y_pred = np.array([0.9, 0.8, 0.4, 0.6, 0.7])
print("True Values are:",y_true)
print("Predicted Values are:",y_pred)

True Values are: [1 0 0 1 1]
Predicted Values are: [0.9 0.8 0.4 0.6 0.7]


In [4]:
# Mean Absolute Error(MAE)
# Formula: MAE = (1/n)*Σ|y_true-y_pred|
#1.Compute absolute differences between true and predicted
abs1=(y_true - y_pred)
#2.Take the mean of all absolute differences
mae=np.mean(np.abs(abs1))
print("Mean Absolute Error (MAE):",mae)

Mean Absolute Error (MAE): 0.4


In [6]:
# Mean Squared Error (MSE)
# Formula: MSE = (1/n) * Σ (y_true - y_pred)^2
#1: Compute squared differences
abs1=(y_true - y_pred)
#2: Take the average of these squared values
mse = np.mean((abs1)**2)
print("Mean Squared Error (MSE):",mse)

Mean Squared Error (MSE): 0.21200000000000005


In [7]:
# Root Mean Squared Error (RMSE)
# Formula: RMSE = √MSE
#1:Take square root of the MSE value
rmse = np.sqrt(mse)
print("Root Mean Squared Error(RMSE):",rmse)

Root Mean Squared Error(RMSE): 0.46043457732885357


In [9]:
# Binary Cross Entropy (BCE)
# Formula: BCE = - (1/n) * Σ [ y_true log(y_pred) + (1 − y_true) log(1 − y_pred) ]
#1: For each sample:If y_true = 1 then use log(y_pred) else If y_true = 0 then use log(1 - y_pred)
bce=np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))
#2: Compute the negative average of all those values
bce=-bce
print("Binary Cross Entropy Loss:", bce)


Binary Cross Entropy Loss: 0.6186249239125281


In [11]:
# Categorical Cross Entropy (Multi-class Example)
# y_true uses one-hot encoding: only the correct class has value 1
# 3 samples, 3 classes
y_true = np.array([[1,0,0], [0,1,0],[0,0,1]])
# y_pred contains predicted class probabilities from softmax
y_pred = np.array([[0.8,0.1,0.1],[0.2,0.6,0.2],[0.1,0.2,0.7]])
#1: Take the natural log of predicted probabilities
log_preds = np.log(y_pred)
#2: Multiply y_true with log_preds → picks only the log of correct class
correct_cls_log = y_true * log_preds
#3: Sum across classes for each sample
sum_per_sample = np.sum(correct_cls_log, axis=1)
#4: Take the mean across all samples
loss_mean = np.mean(sum_per_sample)
#5: Apply negative sign (CCE is negative average log likelihood)
cce = -loss_mean
print("Categorical Cross Entropy Loss:",cce)


Categorical Cross Entropy Loss: 0.3635480396729776


In [12]:
print("\nTrue Values are:", y_true)
print("\nPredicted Values are:", y_pred)
print("\nMean Absolute Error (MAE):", mae)
print("\nMean Squared Error (MSE):", mse)
print("\nRoot Mean Squared Error (RMSE):", rmse)
print("\nBinary Cross Entropy Loss:", bce)
print("\nCategorical Cross Entropy Loss:", cce)


True Values are: [[1 0 0]
 [0 1 0]
 [0 0 1]]

Predicted Values are: [[0.8 0.1 0.1]
 [0.2 0.6 0.2]
 [0.1 0.2 0.7]]

Mean Absolute Error (MAE): 0.4

Mean Squared Error (MSE): 0.21200000000000005

Root Mean Squared Error (RMSE): 0.46043457732885357

Binary Cross Entropy Loss: 0.6186249239125281

Categorical Cross Entropy Loss: 0.3635480396729776
